# Generated by Django 3.2.9 on 2021-12-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow_unique_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
