# Generated by Django 3.2.9 on 2021-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='private',
        ),
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
