# Generated by Django 3.2.9 on 2021-11-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.Tags'),
        ),
    ]
