# Generated by Django 3.2.9 on 2021-11-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211108_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(blank=True, default='pattern.jpg', null=True, upload_to='uploaded'),
        ),
    ]
