# Generated by Django 3.2.9 on 2021-11-09 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20211109_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_x', models.ImageField(blank=True, null=True, upload_to='uploaded')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
    ]
